pipeline {

 agent any
    stages {
        stage("build image") {
            steps {
                script {
                    sh "cd src/python; sudo podman build -t test/program:latest ."
                }
            }
        }
        
         stage("login dockerhub") {
            steps {
            
                     withCredentials([usernamePassword(credentialsId: 'DOCKERHUBID', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                    sh '''
                        sudo podman login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD docker.io                      
                    '''

                   
                }
            }
        }
        
        
         stage("push is dockerhub") {
            steps {
                script {
                    sh "cd src/python; sudo podman images; sudo podman push localhost/test/program:latest samys288/mypython:latest"
                
                }
            }
        }

             stage("deploy in k3s") {
            steps {
                script {
                    sh "sudo /usr/local/bin/k3s kubectl create deployment mspython --image=samys288/mypython:latest"
                    sh "sudo /usr/local/bin/k3s kubectl expose deployment mspython --port=9191 --target-port=8080 --type=ClusterIP"
                }
            }
        }

     
    }
}
