pipeline {

 agent any
    stages {
        stage("build image") {
            steps {
                script {
                    sh "sudo podman build -t test/program:latest ."
                }
            }
        }
        
         stage("push in dockerhub") {
            steps {
                script {
                    sh "sudo podman push localhost/test/program:latest samys288/mypython:latest"
                }
            }
        }
        
        
         stage("deploy in k3s") {
            steps {
                script {
                    sh "sudo kubectl create deployment mspython --image=samys288/mypython:latest"
                    sh "sudo kubectl expose deployment mspython --port=9191 --target-port=8080 --type=ClusterIP"
                }
            }
        }
    }
}
