apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-svc-mspython
  name: dev-svc-mspython
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9191
    protocol: TCP
    targetPort: 8080
  selector:
    app: dev-mspython
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
