apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-09-15T04:12:22Z"
  labels:
    app: mspython
  name: mspython
  namespace: default
  resourceVersion: "978"
  uid: 0df2b088-fd10-44c0-b97f-b0fad38fc3b6
spec:
  clusterIP: 10.43.143.241
  clusterIPs:
  - 10.43.143.241
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9191
    protocol: TCP
    targetPort: 8080
  selector:
    app: mspython
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
