apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-09-15T04:12:21Z"
  generation: 1
  labels:
    app: mspython
  name: mspython
  namespace: default
  resourceVersion: "992"
  uid: 2ab8de89-3da7-40de-adf4-4117cc1669d6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mspython
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mspython
    spec:
      containers:
      - image: samys288/mypython:latest
        imagePullPolicy: Always
        name: mypython
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-09-15T04:12:28Z"
    lastUpdateTime: "2023-09-15T04:12:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-09-15T04:12:21Z"
    lastUpdateTime: "2023-09-15T04:12:28Z"
    message: ReplicaSet "mspython-c5dd5fddd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
